In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report , confusion_matrix
import joblib

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
df['target'] = data.target

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [9]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
df['target_names'] = df['target'].map({i:name for i ,name in enumerate(data.target_names)})

In [11]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
 5   target_names       150 non-null    object 
dtypes: float64(4), int32(1), object(1)
memory usage: 6.6+ KB


In [14]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [15]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [16]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [17]:
binary_df = df[df['target'] !=2]

In [18]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [19]:
x_binary = binary_df[['sepal length (cm)',	'sepal width (cm)',	'petal length (cm)',	'petal width (cm)'	]]

In [20]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [21]:
y_binary = binary_df['target']

In [22]:
x_train , x_test , y_train,y_test = train_test_split(x_binary,y_binary , test_size= .2)

In [23]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.436250          3.071250           2.841250   
std             0.639074          0.460653           1.442457   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.100000           2.450000   
75%             5.825000          3.400000           4.325000   
max             7.000000          4.100000           5.100000   

       petal width (cm)  
count         80.000000  
mean           0.790000  
std            0.566937  
min            0.100000  
25%            0.200000  
50%            0.800000  
75%            1.300000  
max            1.800000

In [24]:
x_binary.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         100.000000        100.000000         100.000000   
mean            5.471000          3.099000           2.861000   
std             0.641698          0.478739           1.449549   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.050000           2.450000   
75%             5.900000          3.400000           4.325000   
max             7.000000          4.400000           5.100000   

       petal width (cm)  
count        100.000000  
mean           0.786000  
std            0.565153  
min            0.100000  
25%            0.200000  
50%            0.800000  
75%            1.300000  
max            1.800000

In [25]:
scaler = StandardScaler()
x_train  = scaler.fit_transform(x_train)

In [26]:
x_test = scaler.transform(x_test)

In [27]:
x_train


array([[ 0.25784654, -0.15564768,  0.87814874,  0.90524621],
       [-0.52947114,  1.59197541, -0.93570367, -0.86974636],
       [-0.84439821,  0.0628052 , -0.93570367, -1.04724561],
       [-0.68693468,  0.49971098, -1.00546722, -1.04724561],
       [-0.52947114,  0.93661675, -1.00546722, -1.04724561],
       [-0.84439821, -1.466365  ,  0.3200403 ,  0.37274844],
       [ 1.51755483,  0.28125809,  1.15720295,  1.26024472],
       [-1.31678882,  0.0628052 , -0.93570367, -1.04724561],
       [-1.00186175,  0.71816386, -0.65664945, -1.04724561],
       [-1.63171589,  0.28125809, -1.07523078, -1.04724561],
       [-0.52947114,  1.59197541, -0.86594011, -1.04724561],
       [ 0.73023715, -0.15564768,  0.94791229,  1.26024472],
       [-0.05708053, -0.15564768,  1.15720295,  1.26024472],
       [-0.68693468,  0.93661675, -1.07523078, -0.86974636],
       [ 0.41531008,  1.59197541, -0.79617656, -0.86974636],
       [ 0.88770068, -1.90327077,  0.80838518,  0.37274844],
       [ 0.100383  , -1.

In [28]:
svm_binary = SVC(kernel='rbf',C=60.0,probability=True)

In [29]:
svm_binary.fit(x_train,y_train)

SVC(C=60.0, probability=True)

In [30]:
svm_binary.predict(x_test)

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [31]:
print("binary class classification report:\n",classification_report(y_test ,svm_binary.predict(x_test) ))

binary class classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [32]:
confusion_matrix(y_test ,svm_binary.predict(x_test))

array([[10,  0],
       [ 0, 10]], dtype=int64)

In [33]:
joblib.dump(svm_binary ,'svm_binary.pkl')

['svm_binary.pkl']

In [34]:
x_multi = df[['sepal length (cm)',	'sepal width (cm)',	'petal length (cm)',	'petal width (cm)'	]]

In [35]:
x_multi 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [36]:
y_multi = df['target']

In [37]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [38]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi = train_test_split(x_multi,y_multi,test_size=.2)

In [39]:
svm_multi = SVC(kernel="linear")

In [40]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear')

In [41]:
svm_multi.predict(x_test_multi)

array([2, 2, 0, 2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1,
       1, 1, 2, 0, 0, 1, 1, 0])

In [42]:
print("report for multi class svc \n",classification_report(y_test_multi ,svm_multi.predict(x_test_multi) ))

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [43]:
confusion_matrix(y_test_multi ,svm_multi.predict(x_test_multi))

array([[10,  0,  0],
       [ 0, 14,  0],
       [ 0,  0,  6]], dtype=int64)

In [44]:
joblib.dump(svm_multi,"svm_multi.pkl")

['svm_multi.pkl']

In [45]:
###logistics practical

In [46]:
#this is binary data 
x_train , x_test , y_train,y_test 

(array([[ 0.25784654, -0.15564768,  0.87814874,  0.90524621],
        [-0.52947114,  1.59197541, -0.93570367, -0.86974636],
        [-0.84439821,  0.0628052 , -0.93570367, -1.04724561],
        [-0.68693468,  0.49971098, -1.00546722, -1.04724561],
        [-0.52947114,  0.93661675, -1.00546722, -1.04724561],
        [-0.84439821, -1.466365  ,  0.3200403 ,  0.37274844],
        [ 1.51755483,  0.28125809,  1.15720295,  1.26024472],
        [-1.31678882,  0.0628052 , -0.93570367, -1.04724561],
        [-1.00186175,  0.71816386, -0.65664945, -1.04724561],
        [-1.63171589,  0.28125809, -1.07523078, -1.04724561],
        [-0.52947114,  1.59197541, -0.86594011, -1.04724561],
        [ 0.73023715, -0.15564768,  0.94791229,  1.26024472],
        [-0.05708053, -0.15564768,  1.15720295,  1.26024472],
        [-0.68693468,  0.93661675, -1.07523078, -0.86974636],
        [ 0.41531008,  1.59197541, -0.79617656, -0.86974636],
        [ 0.88770068, -1.90327077,  0.80838518,  0.37274844],
        

In [47]:
#this is multi class data
x_train_multi , x_test_multi , y_train_multi , y_test_multi

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 124                6.7               3.3                5.7               2.1
 23                 5.1               3.3                1.7               0.5
 24                 4.8               3.4                1.9               0.2
 105                7.6               3.0                6.6               2.1
 118                7.7               2.6                6.9               2.3
 ..                 ...               ...                ...               ...
 13                 4.3               3.0                1.1               0.1
 18                 5.7               3.8                1.7               0.3
 89                 5.5               2.5                4.0               1.3
 45                 4.8               3.0                1.4               0.3
 90                 5.5               2.6                4.4               1.2
 
 [120 rows x 4 columns],
      sepal length (cm)  

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
x_train

array([[ 0.25784654, -0.15564768,  0.87814874,  0.90524621],
       [-0.52947114,  1.59197541, -0.93570367, -0.86974636],
       [-0.84439821,  0.0628052 , -0.93570367, -1.04724561],
       [-0.68693468,  0.49971098, -1.00546722, -1.04724561],
       [-0.52947114,  0.93661675, -1.00546722, -1.04724561],
       [-0.84439821, -1.466365  ,  0.3200403 ,  0.37274844],
       [ 1.51755483,  0.28125809,  1.15720295,  1.26024472],
       [-1.31678882,  0.0628052 , -0.93570367, -1.04724561],
       [-1.00186175,  0.71816386, -0.65664945, -1.04724561],
       [-1.63171589,  0.28125809, -1.07523078, -1.04724561],
       [-0.52947114,  1.59197541, -0.86594011, -1.04724561],
       [ 0.73023715, -0.15564768,  0.94791229,  1.26024472],
       [-0.05708053, -0.15564768,  1.15720295,  1.26024472],
       [-0.68693468,  0.93661675, -1.07523078, -0.86974636],
       [ 0.41531008,  1.59197541, -0.79617656, -0.86974636],
       [ 0.88770068, -1.90327077,  0.80838518,  0.37274844],
       [ 0.100383  , -1.

In [50]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train , y_train)

LogisticRegression()

In [51]:
logistics_binary.predict(x_test)

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [52]:
print("classificaiotn report \n" , classification_report(y_test,logistics_binary.predict(x_test) ))

classificaiotn report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [53]:
confusion_matrix(y_test,logistics_binary.predict(x_test) )

array([[10,  0],
       [ 0, 10]], dtype=int64)

In [54]:
joblib.dump(logistics_binary , "logistics_binary.pkl")

['logistics_binary.pkl']

In [55]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 124                6.7               3.3                5.7               2.1
 23                 5.1               3.3                1.7               0.5
 24                 4.8               3.4                1.9               0.2
 105                7.6               3.0                6.6               2.1
 118                7.7               2.6                6.9               2.3
 ..                 ...               ...                ...               ...
 13                 4.3               3.0                1.1               0.1
 18                 5.7               3.8                1.7               0.3
 89                 5.5               2.5                4.0               1.3
 45                 4.8               3.0                1.4               0.3
 90                 5.5               2.6                4.4               1.2
 
 [120 rows x 4 columns],
      sepal length (cm)  

In [56]:
x_train_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
124                6.7               3.3                5.7               2.1
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
105                7.6               3.0                6.6               2.1
118                7.7               2.6                6.9               2.3
..                 ...               ...                ...               ...
13                 4.3               3.0                1.1               0.1
18                 5.7               3.8                1.7               0.3
89                 5.5               2.5                4.0               1.3
45                 4.8               3.0                1.4               0.3
90                 5.5               2.6                4.4               1.2

[120 rows x 4 columns]

In [57]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)

In [58]:
logistics_ovr.fit(x_train_multi,y_train_multi)

c:\Users\bhara\anaconda3\envs\medibot\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [59]:
logistics_ovr.predict(x_test_multi)

array([2, 2, 0, 2, 2, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0, 1,
       1, 2, 2, 0, 0, 1, 1, 0])

In [60]:
print("classificatoin repost for ovr logistics \n" , classification_report(y_test_multi , logistics_ovr.predict(x_test_multi)))

classificatoin repost for ovr logistics 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.79      0.88        14
           2       0.67      1.00      0.80         6

    accuracy                           0.90        30
   macro avg       0.89      0.93      0.89        30
weighted avg       0.93      0.90      0.90        30



In [61]:
confusion_matrix(y_test_multi , logistics_ovr.predict(x_test_multi))

array([[10,  0,  0],
       [ 0, 11,  3],
       [ 0,  0,  6]], dtype=int64)

In [63]:
joblib.dump(logistics_ovr ,'logistics_ovr.pkl')

['logistics_ovr.pkl']

In [64]:
logistics_multinomial  = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=2000)

In [65]:
logistics_multinomial.fit(x_train_multi,y_train_multi)

c:\Users\bhara\anaconda3\envs\medibot\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [66]:
logistics_multinomial.predict(x_test_multi)

array([2, 2, 0, 2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0, 1,
       1, 1, 2, 0, 0, 1, 1, 0])

In [67]:
confusion_matrix(y_test_multi,logistics_multinomial.predict(x_test_multi) )

array([[10,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  6]], dtype=int64)

In [68]:
print("the classificatoin report for multinomila multi class logistics is \n" , classification_report(y_test_multi,logistics_multinomial.predict(x_test_multi) ))

the classificatoin report for multinomila multi class logistics is 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.93      0.96        14
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



In [69]:
joblib.dump(logistics_multinomial ,'logistics_multinomial.pkl')

['logistics_multinomial.pkl']